name: Check for New Layoffs

on:
  schedule:
    # Run every hour (you can change this)
    - cron: '0 * * * *'
  workflow_dispatch:  # This lets you run it manually for testing

jobs:
  check-layoffs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    
    - name: Run layoff checker
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        python checker.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name "Layoff Bot"
        git config --global user.email "bot@example.com"
        git add seen_companies.json || true
        git diff --staged --quiet || (git commit -m "Update seen companies list" && git push)
